### ISSUE TITLE
ERROR ReferenceError: robot is not defined

### ISSUE THREAD

**Issue by xgbn** [aaaschmitt/hubot-googledrive-search#1]
I met this Error....
Error happens with `@hubot drive search title=<title>`

Here is the traceback:

```
  at search (/Users/xiangbinhu/GitHub/rabbito/node_modules/hubot-googledrive-search/src/hubot-googledrive-search.js:60:24)
  at TextListener.callback (/Users/xiangbinhu/GitHub/rabbito/node_modules/hubot-googledrive-search/src/hubot-googledrive-search.js:182:9)
  at executeListener (/Users/xiangbinhu/GitHub/rabbito/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/Users/xiangbinhu/GitHub/rabbito/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /Users/xiangbinhu/GitHub/rabbito/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/Users/xiangbinhu/GitHub/rabbito/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/Users/xiangbinhu/GitHub/rabbito/node_modules/async/lib/async.js:268:15)
  at /Users/xiangbinhu/GitHub/rabbito/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at nextTickCallbackWith0Args (node.js:433:9)
  at process._tickCallback (node.js:362:13)
```

I am trying to look into it. Please check this issue. Thanks!

**Comment by aaaschmitt** [comment]
I'll take a look into it. I've been busy lately.

**Comment by aaaschmitt** [comment]
Make sure you are using the most recent implementation. The query you provided did not error for me. Comment again here if you are still having problems
